package main

import (
	"context"
	"testing"
	"text/template"
	"time"

	"github.com/Masterminds/sprig/v3"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

// mockClientWithCapture extends mockClient to capture UpdateDocuments args
type mockClientWithCapture struct {
	*mockClient
	lastSuggestions []DocumentSuggestion
}

func (m *mockClientWithCapture) UpdateDocuments(ctx context.Context, documents []DocumentSuggestion, db *gorm.DB, isUndo bool) error {
	m.updateDocsCalled = true
	m.lastSuggestions = documents
	return nil
}

func TestClassifyDocument_Exists(t *testing.T) {
	autoTag = "paperless-gpt-auto"
	autoOcrTag = "paperless-gpt-ocr-auto"

	// Disable all generation to avoid nil LLM panic
	origTitle := autoGenerateTitle
	origTags := autoGenerateTags
	origCorr := autoGenerateCorrespondents
	origDate := autoGenerateCreatedDate
	origDocType := autoGenerateDocumentType
	autoGenerateTitle = "false"
	autoGenerateTags = "false"
	autoGenerateCorrespondents = "false"
	autoGenerateCreatedDate = "false"
	autoGenerateDocumentType = "false"
	defer func() {
		autoGenerateTitle = origTitle
		autoGenerateTags = origTags
		autoGenerateCorrespondents = origCorr
		autoGenerateCreatedDate = origDate
		autoGenerateDocumentType = origDocType
	}()

	env := setupTest(t)
	defer env.teardown()

	// Register mock responses needed by classifyDocument -> generateDocumentSuggestions
	setupTestCase(&OCRTestCase{documents: []TestDocument{}}, env)

	client := newMockClient(env.client)
	app := &App{
		Client:   client,
		Database: env.db,
	}

	doc := Document{
		ID:      1,
		Title:   "Test Doc",
		Content: "OCR text about an electric bill",
		Tags:    []string{autoOcrTag},
	}

	ctx := context.Background()
	docLogger := documentLogger(doc.ID)

	// classifyDocument should exist and return a suggestion (with all generation disabled)
	suggestion, err := app.classifyDocument(ctx, doc, docLogger)
	require.NoError(t, err)
	assert.NotNil(t, suggestion)
	assert.Equal(t, 1, suggestion.ID)
}

func TestProcessAutoOcrTagDocuments_ChainingDisabled(t *testing.T) {
	autoOcrTag = "paperless-gpt-ocr-auto"
	autoTag = "paperless-gpt-auto"
	pdfOCRCompleteTag = "paperless-gpt-ocr-complete"

	// Ensure chaining is disabled
	origChaining := autoOcrThenClassify
	autoOcrThenClassify = false
	defer func() { autoOcrThenClassify = origChaining }()

	env := setupTest(t)
	defer env.teardown()

	ctx, cancel := context.WithTimeout(context.Background(), 1500*time.Millisecond)
	defer cancel()

	base := newMockClient(env.client)
	client := &mockClientWithCapture{mockClient: base}
	client.AddTag(autoOcrTag, 2)

	doc := Document{
		ID:      1,
		Title:   "Test Doc",
		Content: "Original tesseract text",
		Tags:    []string{autoOcrTag},
	}
	client.AddDocument(doc, []string{autoOcrTag})

	app := &App{
		Client:         client,
		Database:       env.db,
		ocrProvider:    &mockOCRProvider{text: "Better OCR text"},
		docProcessor:   &mockDocumentProcessor{mockText: "Better OCR text"},
		ocrProcessMode: "image",
	}

	count, err := app.processAutoOcrTagDocuments(ctx)
	require.NoError(t, err)
	assert.Equal(t, 1, count)
	assert.True(t, client.updateDocsCalled)

	// With chaining disabled, UpdateDocuments should only have OCR content, no classification
	require.Len(t, client.lastSuggestions, 1)
	assert.Equal(t, "Better OCR text", client.lastSuggestions[0].SuggestedContent)
	// No title suggestion when chaining is disabled
	assert.Empty(t, client.lastSuggestions[0].SuggestedTitle)
}

func TestProcessAutoOcrTagDocuments_ChainingEnabled_ClassifySucceeds(t *testing.T) {
	autoOcrTag = "paperless-gpt-ocr-auto"
	autoTag = "paperless-gpt-auto"
	pdfOCRCompleteTag = "paperless-gpt-ocr-complete"

	// Initialize templates
	var err error
	ocrTemplate, err = template.New("ocr").Funcs(sprig.FuncMap()).Parse("OCR prompt")
	require.NoError(t, err)

	origChaining := autoOcrThenClassify
	autoOcrThenClassify = true
	defer func() { autoOcrThenClassify = origChaining }()

	// Disable all generation so classifyDocument succeeds without an LLM
	origTitle := autoGenerateTitle
	origTags := autoGenerateTags
	origCorr := autoGenerateCorrespondents
	origDate := autoGenerateCreatedDate
	origDocType := autoGenerateDocumentType
	autoGenerateTitle = "false"
	autoGenerateTags = "false"
	autoGenerateCorrespondents = "false"
	autoGenerateCreatedDate = "false"
	autoGenerateDocumentType = "false"
	defer func() {
		autoGenerateTitle = origTitle
		autoGenerateTags = origTags
		autoGenerateCorrespondents = origCorr
		autoGenerateCreatedDate = origDate
		autoGenerateDocumentType = origDocType
	}()

	env := setupTest(t)
	defer env.teardown()

	// Register mock responses needed by classifyDocument
	setupTestCase(&OCRTestCase{
		documents: []TestDocument{
			{ID: 1, Title: "Test Doc", Tags: []string{autoOcrTag}},
		},
	}, env)

	ctx, cancel := context.WithTimeout(context.Background(), 1500*time.Millisecond)
	defer cancel()

	base := newMockClient(env.client)
	client := &mockClientWithCapture{mockClient: base}
	client.AddTag(autoOcrTag, 2)
	client.AddTag(autoTag, 1)

	doc := Document{
		ID:      1,
		Title:   "Test Doc",
		Content: "Original tesseract text",
		Tags:    []string{autoOcrTag},
	}
	client.AddDocument(doc, []string{autoOcrTag})

	app := &App{
		Client:         client,
		Database:       env.db,
		ocrProvider:    &mockOCRProvider{text: "Better OCR text"},
		docProcessor:   &mockDocumentProcessor{mockText: "Better OCR text"},
		ocrProcessMode: "image",
	}

	count, err := app.processAutoOcrTagDocuments(ctx)
	require.NoError(t, err)
	assert.Equal(t, 1, count)
	assert.True(t, client.updateDocsCalled)

	// With chaining enabled, both OCR content AND classification should be applied
	require.Len(t, client.lastSuggestions, 1)
	assert.Equal(t, "Better OCR text", client.lastSuggestions[0].SuggestedContent)
	// AUTO_TAG should be in RemoveTags (chaining removes both OCR and auto tags)
	assert.Contains(t, client.lastSuggestions[0].RemoveTags, autoTag)
	assert.Contains(t, client.lastSuggestions[0].RemoveTags, autoOcrTag)
}
