services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - node_modules/
            - .git/
